### PR TITLE
Address Digital-1419: Modify descriptive metadata for RFTA Artists.

### PR DESCRIPTION
**Pull request by markpbaggett**
# What Does This Do

1. Adds a `not(@encoding)` rule to date mappings.
2. Maps specific related resources to `Related Resource`.

# How Can I Test

Take your favorite piece of art and do something like this. 

https://digital.lib.utk.edu/assemble/manifest/rftaart/1?update=1

You can use see it in a viewer if it's helpful here following same pattern:

https://uv-v4.netlify.app/#?manifest=https://digital.lib.utk.edu/assemble/manifest/rftaart/1

Keep in mind that the way this is styled in a viewer does not necessarily mean it will be that way for us (nectar).

### CODE REVIEW

**Review by mlhale7 — COMMENTED** [review]
So, I know that we are focused on RFTA Artists particularly here, but I think it's important to note that the general RFTA collection might throw a wrench in this. Currently the general RFTA collection only has a date with @encoding. Here's an example - https://uv-v4.netlify.app/#?manifest=https://digital.lib.utk.edu/assemble/manifest/rfta/6 Is there any way to take originInfo/dateCreated[not(@encoding)]|originInfo/dateOther when it exists but take the @encoding value if no other value exists? We can add date values without @encoding if needed for this particular collection, but I'm sure there are other instances in digital collections where this might pose problems.

**Comment by markpbaggett** [comment]
@mlhale7 if that's the case, this won't work and will need a more complex way of dealing with what the date is. I'll work on something else.

**Comment by markpbaggett** [comment]
@mlhale7 I've changed this again, but I've dropped dateOther.  This is already messy, and I feel like dateOther just makes things worse. Now, we grab human readable date from dateCreated and use it unless it does not exist.  When it doesn't we use the machine date.

**Review by mlhale7 — APPROVED** [review]
I think this works for the vast majority of our collections and will serve us well. There are cases where we use dateOther in conjunction with dateCreated, so I think it's okay to drop and remove some noise. This is an example we're well end up with no date value since only a dateOther is present - https://digital.lib.utk.edu/collections/islandora/object/volvoices%3A11880

**Comment by markpbaggett** [comment]
How is `dateOther` different than other dates in that context?

**Review by mlhale7 — COMMENTED** [review]
It isn't any different. As I noted earlier in chat, these values are in dateOther simply due to the out of the box LC transform. LC just didn't want to specify either dateIssued or dateCreated because it could potentially be either value coming from a generic dc:date. Typically in our collections dateOther values are associated with dateCreated - hence why the initial mapping including dateOther along with dateCreated.

**Comment by markpbaggett** [comment]
@mlhale7 If that's the case, does it just make sense to fix the dates in those records and use `dateCreated` or `dateIssued`? If so, I'm happy to write a transform to regenerate the XML for those records.

**Comment by mlhale7** [comment]
@markpbaggett - it does make sense, though I'd like to handle it. I'll have the students go through and identify any items that should have dateIssued instead (as those items do exist). Since we plan to do this work, this can definitely be merged.

**Comment by mlhale7** [comment]
Here's a ticket - https://jirautk.atlassian.net/browse/DIGITAL-1420

**Pull request merged**
