### PR TITLE
Add Abstract and other things to manifest.

### PR DESCRIPTION
**Pull request by markpbaggett**
## What Does This Do

1. Adds abstract to metadata.
2. Adds a Spanish abstract and Spanish title to metadata.
3. Refactors things to allow for metadata elements to be in other languages. (not a great approach, but okay for now).
4. Only allows for labels in English (for now).

## How can you test?

Check this branch out in utk_digital and do an update on an object with a Spanish RFTA MODS record.  Look at the updated manifest in assemble.

### CODE REVIEW

**Review by mlhale7 — APPROVED** [review]
Approving as this improves the current manifest by at least including the Spanish language information. In the future action should be taken to make the language associated with this information be correct (right now it lists Spanish content as English)
Screen Shot 2021-11-01 at 4 09 18 PM
.

**Comment by markpbaggett** [comment]
@mlhale7 either my code doesn't work, or your test failed.

**Comment by mlhale7** [comment]
I checked out the branch, vagranted up, updated a metadata record in the virtual environment and in browser, and then viewed it in. I'll retry.

**Comment by mlhale7** [comment]
I'm getting the same result as previously. If others have a chance to quickly review, please do so.

**Comment by markpbaggett** [comment]
Is your manifest cached?

**Comment by markpbaggett** [comment]
This uses the Julia Rodriguez example from Islandora and this branch:

image

and:

image

**Pull request merged**
